# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-12 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('game_id', models.CharField(max_length=15)),
                ('away_id', models.CharField(max_length=15)),
                ('home_id', models.CharField(max_length=15)),
                ('away_team', models.CharField(max_length=3)),
                ('home_team', models.CharField(max_length=3)),
                ('away_pts', models.FloatField()),
                ('home_pts', models.FloatField()),
                ('vegas_spread_str', models.CharField(max_length=20)),
                ('pred_spread_str', models.CharField(max_length=20)),
                ('pick_str', models.CharField(max_length=20)),
                ('team_covered', models.CharField(max_length=3)),
                ('team_picked', models.CharField(max_length=3)),
                ('result', models.CharField(max_length=10)),
                ('best_bet', models.CharField(max_length=3)),
            ],
        ),
    ]
