# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-10 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('game_id', models.CharField(max_length=10)),
                ('away_team', models.CharField(max_length=3)),
                ('home_team', models.CharField(max_length=3)),
                ('pts_away', models.FloatField()),
                ('pts_home', models.FloatField()),
                ('vegas_spread_str', models.CharField(max_length=15)),
                ('pred_spread_str', models.CharField(max_length=15)),
                ('pick_str', models.CharField(max_length=15)),
                ('team_covered', models.CharField(max_length=3)),
                ('team_picked', models.CharField(max_length=3)),
                ('result', models.CharField(max_length=10)),
                ('best_bet', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
